# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-03 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='is_user_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
