# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_market_is_user_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_trade', models.DecimalField(decimal_places=18, max_digits=36)),
                ('high_trade', models.DecimalField(decimal_places=18, max_digits=36)),
                ('low_trade', models.DecimalField(decimal_places=18, max_digits=36)),
                ('current_volume', models.DecimalField(decimal_places=18, max_digits=36)),
                ('timestamp', models.DateTimeField()),
                ('ask', models.DecimalField(decimal_places=18, max_digits=36)),
                ('bid', models.DecimalField(decimal_places=18, max_digits=36)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markets.Market')),
            ],
        ),
    ]
