# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-03 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_market_is_user_enabled'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(blank=True, choices=[(1, 'internal'), (2, 'external')])),
                ('is_user_enabled', models.BooleanField(default=False)),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='markets.Market')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='markets.Market')),
            ],
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='reciever',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Transfer',
        ),
    ]
