# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20171103_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='reciever',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
